routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/all-applied-jobs', 'HomeController@allJobApplied')->name('all.applied.jobs');

Route::post('/post-create', 'PostController@store')->name('post.create');
Route::get('/admin-dashboard', 'AdminController@index')->name('admin.dashboard');
Route::get('/users-post', 'AdminController@showUsersPost')->name('users.post');
Route::get('/applicant-login', 'ApplicantController@showApplicantLoginForm')->name('applicant.login');
Route::get('/applicant-register', 'ApplicantController@showApplicantRegForm')->name('applicant.register');
Route::post('/applicant-registration', 'ApplicantController@showApplicantReg')->name('applicant.registration');
Route::post('/applicant/login', 'ApplicantController@applicantLoginSystem')->name('applicant.login.system');
Route::post('/applicant-profile-update/{applicant}', 'ApplicantController@applicationProfileUpdate')->name('applicant.profile.update');
Route::get('/applicant-dashboard', 'ApplicantController@showApplicantDashboard')->name('applicant.dashboard');
Route::get('/all-jobs-circular', 'ApplicantController@showAllJobsCircular')->name('all.jobs.circular');
Route::post('/job-applied', 'ApplicantController@jobApplied')->name('job.applied');
Route::post('/applicant.logout', 'ApplicantController@applicantLogout')->name('applicant.logout');

app/Applicant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Applicant extends Model
{
    public function applied()
    {
        return $this->hasMany(Applied::class, 'user_id', 'id');
    }
}

app/JobPost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class JobPost extends Model
{
    protected $guarded = [];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function applied()
    {
        return $this->belongsTo(Applicant::class);
    }

    public function getCountryAttribute($value)
    {
        return ucfirst($value);
    }
}

app/Http/Controllers/ApplicantController.php
<?php

namespace App\Http\Controllers;

use App\Applicant;
use App\Applied;
use App\JobPost;
use Illuminate\Http\Request;
use Session;
class ApplicantController extends Controller
{
    public function showApplicantLoginForm()
    {
        return view('applicant.login');
    }

    public function applicantLoginSystem(Request $request)
    {

        $applicant = Applicant::where('email', $request->email)->first();
        if ($applicant){
            if (password_verify($request->password, $applicant->password)){
                Session::put('id', $applicant->id);
                Session::put('first_name', $applicant->first_name);
                Session::put('last_name', $applicant->last_name);
                return redirect('applicant-dashboard');
            }else{
                return redirect()->back()->with('message', 'Password dose not match');
            }

        }else{
            return redirect()->back()->with('message', 'E-mail dose not match');
        }

    }

    public function showApplicantRegForm()
    {
        return view('applicant.register');
    }

    public function showApplicantReg(Request $request)
    {
        try {
            $this->validate($request, [
                'first_name' => 'required',
                'last_name' => 'required',
                'email' => 'required|unique:applicants',
                'password' => 'required',
            ]);

            $applicant = new Applicant();
            $applicant->first_name = $request->first_name;
            $applicant->last_name = $request->last_name;
            $applicant->email = $request->email;
            $applicant->password = bcrypt($request->password);
            $applicant->save();
            Session::put('id', $applicant->id);
            Session::put('first_name', $applicant->first_name);
            Session::put('last_name', $applicant->last_name);
            return redirect('applicant-dashboard');

        }catch (\Exception $exception) {
            return  redirect()->back()->with('error', $exception->getMessage());
        }
    }

    public function showApplicantDashboard()
    {
        $applicant = Applicant::where('id', Session::get('id'))->first();
        return view('applicant.dashboard', compact('applicant'));
    }

    public function applicationProfileUpdate(Request $request, Applicant $applicant)
    {
        try {
//            $this->validate($request, [
//                'first_name' => 'required',
//                'last_name' => 'required',
//                'password' => 'required',
//            ]);

            $profilePic = time().'_'.'.'. $request->profile_picture->extension();
            $request->profile_picture->move(public_path('profile-pictures'), $profilePic);

            $resume = time().'_'.'.'. $request->resume->extension();
            $request->resume->move(public_path('resume'), $resume);

            $applicant->first_name = $request->first_name;
            $applicant->last_name = $request->last_name;
            $applicant->email = $request->email;
            $applicant->skills = $request->skills;
            $applicant->password = bcrypt($request->password);
            $applicant->profile_picture = $profilePic;
            $applicant->resume = $resume;
            $applicant->save();
            Session::put('id', $applicant->id);
            Session::put('first_name', $applicant->first_name);
            Session::put('last_name', $applicant->last_name);
            return redirect()->back()->with('message', 'profile updated');

        }catch (\Exception $exception) {
            return  redirect()->back()->with('error', $exception->getMessage());
        }
    }

    public function showAllJobsCircular()
    {
        $jobs = JobPost::with('user')->get();
        return view('applicant.jobs', compact('jobs'));
    }

    public function jobApplied(Request $request)
    {
        $applied = new Applied();
        $applied->user_id = $request->user_id;
        $applied->post_id = $request->post_id;
        $applied->applicant_id = Session::get('id');
        $applied->status = 1;
        $applied->save();
        return redirect()->back()->with('message', 'job applied successfully');
    }

    public function applicantLogout(){
        Session::forget('id');
        Session::forget('name');
        return redirect('/');
    }
}

resources/views/applicant/dashboard.blade.php
@extends('layouts.applicant')

@section('content')
    <div class="container">
        <div class="col-md-12">
            @if(Session::get('message'))
                <p class="alert alert-success">{{ Session::get('message') }}</p>
            @endif
                @if(Session::get('error'))
                    <p class="alert alert-danger">{{ Session::get('error') }}</p>
                @endif
            <div class="card">
                <div class="card-header">
                    @if(Session::get('id'))
                    {{ Session::get('first_name') }} {{ Session::get('last_name') }} Dashboard
                    @endif
                    <a href="{{ route('all.jobs.circular') }}" class="float-right">All Job circular</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('applicant.profile.update', $applicant->id) }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ $applicant->first_name }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ $applicant->last_name }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="skills" class="col-md-4 col-form-label text-md-right">Skills</label>

                            <div class="col-md-6">
                                <input id="skills" type="text" class="form-control @error('skills') is-invalid @enderror" name="skills" value="{{ $applicant->skills }}" required autocomplete="skills" autofocus>

                                @error('skills')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $applicant->email }}" required autocomplete="email">

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="" class="col-md-4 col-form-label text-md-right">Profile Picture</label>

                            <div class="col-md-6">
                                <input id="profile_picture" type="file" class="form-control" name="profile_picture" required>
                                <img src="{{ asset('/profile-pictures/'.$applicant->profile_picture) }}" height="100" width="100">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="" class="col-md-4 col-form-label text-md-right">Resume</label>

                            <div class="col-md-6">
                                <input id="resume" type="file" class="form-control" name="resume" required accept="application/pdf">
                                <span class="btn btn-info">{{ $applicant->resume }}</span>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/applicant/jobs.blade.php
@extends('layouts.applicant')

@section('content')
    <div class="container">
        @if(Session::get('message'))
            <p class="alert alert-success">{{ Session::get('message') }}</p>
        @endif
        @if(Session::get('error'))
            <p class="alert alert-danger">{{ Session::get('error') }}</p>
        @endif
        <div class="row">
            @foreach($jobs as $key => $job)
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">{{ $job->job_title }}</div>
                    <div class="card-body">
                        <p>Details : {{ $job->job_description }}</p>
                        <p>Office Location : {{ $job->location }}</p>
                        <p>Country : {{ $job->country }}</p>
                        <p>Salary : {{ number_format($job->salary, 2) }} BDT</p>
                    </div>
                    <form action="{{ route('job.applied', $job->id) }}" method="post">
                        @csrf
                        <input type="hidden" name="post_id" value="{{ $job->id }}">
                        <input type="hidden" name="user_id" value="{{ $job->user->id }}">
                        <button type="submit" class="btn btn-block btn-primary">Apply</button>
                    </form>
                </div>
            </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/applicant/login.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
<div class="container" style="margin-top: 30px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Applicant Login</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('applicant.login.system') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

resources/views/applicant/register.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>

<body>
<div class="container" style="margin-top: 20px;">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @if(Session::get('error'))
                <p class="alert alert-danger">{{ Session::get('error') }}</p>
            @endif
                @if(Session::get('message'))
                    <p class="alert alert-success">{{ Session::get('message') }}</p>
                @endif
            <div class="card">
                <div class="card-header">
                    Applicant Register
                    <a href="{{ url('/') }}" class="btn btn-danger float-right">Back</a>
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('applicant.registration') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="first_name" class="col-md-4 col-form-label text-md-right">First Name</label>

                            <div class="col-md-6">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>

                            <div class="col-md-6">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    Register
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>